# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello? Anyone out there?
description: > # this means to ignore newlines until "baseurl:"
  If someone blogs in the forest but no one reads it, does it make a sound?
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  jimm-domingo

# Build settings
markdown: kramdown

# Output
permalink: /:year/:month/:day/:title/

theme: jekyll-theme-tactile